apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 346790393377.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 346790393377.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: b92d5dab
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
